version: "3.7"

services:
  app:
    build:
      context: .
    restart: on-failure
    env_file:
      - .env
      - .env.-db
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "4500:4500"
    command: >
      /wait-for-it.sh db:5432 -- npm run start:dev
  db:
    image: postgres:14.3-alpine
    restart: on-failure
    env_file:
      - .env.-db
    ports:
      - "5433:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
